application: philoufr-test1
version: 3
runtime: python27
api_version: 1
threadsafe : false

libraries:
- name: webapp2
  version: latest
  
- name: jinja2
  version: latest
  
  
handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /static
  static_dir: static
  
- url: /.*
  script: cavavin.py
